version: '3'

services:
  node:
    image: formater-linter-test
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/app
    ports:
      # ホストのポートとコンテナのポートを接続
      - "3000:3000"
